SSAFY-Python-Study/Pystudy

SWEA/D3/1206. ［S／W 문제해결 기본］ 1일차 － View/README.md, SWEA/D3/1206. ［S／W 문제해결 기본］ 1일차 － View/［S／W 문제해결 기본］ 1일차 － View.py
=> 강수민/3월 6일/개인 문제

SWEA/D3/1208. ［S／W 문제해결 기본］ 1일차 － Flatten/README.md, SWEA/D3/1208. ［S／W 문제해결 기본］ 1일차 － Flatten/［S／W 문제해결 기본］ 1일차 － Flatten.py, SWEA/D3/6485. 삼성시의 버스 노선/README.md, SWEA/D3/6485. 삼성시의 버스 노선/삼성시의 버스 노선.py
=> 강수민/3월 5일/개인 문제

SWEA/D3/10580. 전봇대/README.md, SWEA/D3/10580. 전봇대/전봇대.py, SWEA/D3/20551. 증가하는 사탕 수열/README.md, SWEA/D3/20551. 증가하는 사탕 수열/증가하는 사탕 수열.py
=> 강수민/3월 7일/개인 문제

SWEA/D2/1859. 백만 장자 프로젝트/README.md, SWEA/D2/1859. 백만 장자 프로젝트/백만 장자 프로젝트.py, SWEA/D3/11315. 오목 판정/README.md, SWEA/D3/11315. 오목 판정/오목 판정.py, SWEA/Unrated/1953. ［모의 SW 역량테스트］ 탈주범 검거/README.md, SWEA/Unrated/1953. ［모의 SW 역량테스트］ 탈주범 검거/［모의 SW 역량테스트］ 탈주범 검거.py
=> 강수민/3월 10일/개인문제

SWEA/Unrated/4008. ［모의 SW 역량테스트］ 숫자 만들기/README.md, SWEA/Unrated/4008. ［모의 SW 역량테스트］ 숫자 만들기/［모의 SW 역량테스트］ 숫자 만들기.py
1. SWEA 숫자 만들기
백준에서 유사한 문제를 풀었을 때 라이브러리로 넘겼던 부분을 직접 구현해보니까 아주 뿌듯하네요. 재귀 호출 정복 중에 '재' 정도는 한 것 같아서 아주 좋습니다.
재귀 호출에 매우 겁먹긴 했지만, 기본적인 호출-종료조건-호출 전 로직-호출-호출 후 로직 이라는 구조를 좀 이해하니까 조금이나마 이해할 수 있었던 것 같습니다. 겁먹지 않고 정진하겠습니다.
=> 구하린/3월 12일/개인 문제

SWEA/D4/1861. 정사각형 방/README.md, SWEA/D4/1861. 정사각형 방/정사각형 방.py, SWEA/Unrated/1952. ［모의 SW 역량테스트］ 수영장/README.md, SWEA/Unrated/1952. ［모의 SW 역량테스트］ 수영장/［모의 SW 역량테스트］ 수영장.py
문제풀이 시간에 다뤘던 문제 중 2개 제출하겠습니다..
=> 강수민/3월 14일/개인 문제

SWEA/D2/14229. 백만 개의 정수 정렬/README.md, SWEA/D2/14229. 백만 개의 정수 정렬/백만 개의 정수 정렬.py, SWEA/D4/1232. ［S／W 문제해결 기본］ 9일차 － 사칙연산/README.md, SWEA/D4/1232. ［S／W 문제해결 기본］ 9일차 － 사칙연산/［S／W 문제해결 기본］ 9일차 － 사칙연산.py, SWEA/Unrated/5656. ［모의 SW 역량테스트］ 벽돌 깨기/README.md, SWEA/Unrated/5656. ［모의 SW 역량테스트］ 벽돌 깨기/［모의 SW 역량테스트］ 벽돌 깨기.py
오늘은 오전에 시간이 없어서 많이 풀지는 못했습니다.
SWEA 문제 중 풀지 않은 위주로 풀어보았어요!
=> 조현아/3월 17일/개인문제

SWEA/D3/2806. N－Queen/N－Queen.py, SWEA/D3/2806. N－Queen/README.md, SWEA/D4/1865. 동철이의 일 분배/README.md, SWEA/D4/1865. 동철이의 일 분배/동철이의 일 분배.py
동철이: lambda를 활용해 100으로 나눈 수를 받아오는게 시간줄이기의 핵심이었음
N-Queen: 필요이상으로 for문의 for문을 돌고 있어서 시간을 줄일 수 있는 방법 연구해보기
=> 고영우/ 250318/ 개인문제

SWEA/D3/2806. N－Queen/N－Queen.py, SWEA/D3/2806. N－Queen/README.md
=> 백태균 / 250318 / 개인문제

SWEA/D4/1865. 동철이의 일 분배/README.md, SWEA/D4/1865. 동철이의 일 분배/동철이의 일 분배.py
실습 과제 동철이의 일 분배입니다.
백트래킹과 가지치기를 이용하였습니다!
=> 김나영/3월 18일/개인 문제

SWEA/D6/1795. 인수의 생일 파티/README.md, SWEA/D6/1795. 인수의 생일 파티/인수의 생일 파티.py
D6라고 해서 쫄았지만..... 다행이? 그렇게는 어렵지 않았던 것 같습니다! 함수를 하나 만들고 반대로 for문 돌면서 반대 방향도 계산했어요. 행렬을 반대로 만들어서 하는게 시간을 더 단축시킨다고 해서 그거를 다음에 도전해볼게요!
=> 조현아/3월20일/개인문제

SWEA/D6/1795. 인수의 생일 파티/README.md, SWEA/D6/1795. 인수의 생일 파티/인수의 생일 파티.py
=> 김광현 / 3월 20일 / 개인문제

SWEA/D1/9386. 연속한 1의 개수/README.md, SWEA/D1/9386. 연속한 1의 개수/연속한 1의 개수.py, SWEA/D4/1249. ［S／W 문제해결 응용］ 4일차 － 보급로/README.md, SWEA/D4/1249. ［S／W 문제해결 응용］ 4일차 － 보급로/［S／W 문제해결 응용］ 4일차 － 보급로.py, SWEA/D4/1251. ［S／W 문제해결 응용］ 4일차 － 하나로/README.md, SWEA/D4/1251. ［S／W 문제해결 응용］ 4일차 － 하나로/［S／W 문제해결 응용］ 4일차 － 하나로.py, SWEA/D6/1267. ［S／W 문제해결 응용］ 10일차 － 작업순서/README.md, SWEA/D6/1267. ［S／W 문제해결 응용］ 10일차 － 작업순서/［S／W 문제해결 응용］ 10일차 － 작업순서.py
단순 구현 문제(1), 외 다익스트라, MST 알고리즘 활용 유형을 공부했습니다.
=> 강수민/3월 21일/개인 문제

SWEA/D6/1267. ［S／W 문제해결 응용］ 10일차 － 작업순서/README.md, SWEA/D6/1267. ［S／W 문제해결 응용］ 10일차 － 작업순서/［S／W 문제해결 응용］ 10일차 － 작업순서.py
swea에서 풀었던 작업 순서 문제를 다시 풀어봤습니다. 간단하게 bfs를 사용해서 풀 수 있는 문제였습니다.
=> 김광현 / 3월 25일 / 개인문제

백준/Silver/1003. 피보나치 함수/README.md, 백준/Silver/1003. 피보나치 함수/피보나치 함수.py
1. 백준 1003번 피보나치 함수
DP인 건 알았는데 어떻게 풀어야 하는지 고민하느라 시간이 좀 걸렸네요... 호출 횟수에 이런 비밀이 있을 줄은 몰랐습니다. 재미있는 문제였습니다.
=> 구하린/3월 26일/개인 문제

백준/Silver/30825. 건공펀치 등차수열/README.md, 백준/Silver/30825. 건공펀치 등차수열/건공펀치 등차수열.py
심플하지만 재밌네요
어떤 케이스가 가능한지랑 인덱싱 연습 가볍게 해보기 좋은 거 같습니다
=> 김현우/20250401/개인문제

백준/Gold/17144. 미세먼지 안녕！/README.md, 백준/Gold/17144. 미세먼지 안녕！/미세먼지 안녕！.py
델타를 적용하되 행렬 순서대로 바로 적용하면 뒤에 탐색되는 행렬에 영향을 미침
-> 행렬을 복사하여 그 값을 참조할 수 있도록 함
공기청정기의 경우 네 방향과 거리가 고정이므로 4번의 for문을 활용함
-> 이건 direction_idx를 활용하여 행렬 idx 바깥에 걸리면 방향을 바꿔서 탐색하도록 풀어보려했는데 복잡해지고 자꾸 원하는 값이 안나와 그냥 for 문 4번으로 돌림
=> 고영우/ 250401/ 개인문제

백준/Silver/11726. 2×n 타일링/2×n 타일링.py, 백준/Silver/11726. 2×n 타일링/README.md
간단한 dp문제인데 발상을 못해서 한번 틀렸습니다...........
=> 박효정 / 4월2일 / 개인문제

SWEA/D2/4875. ［파이썬 S／W 문제해결 기본］ 5일차 － 미로/README.md, SWEA/D2/4875. ［파이썬 S／W 문제해결 기본］ 5일차 － 미로/［파이썬 S／W 문제해결 기본］ 5일차 － 미로.py
1. 전에 알고리즘 기간 때 풀었던 미로 문제를 dfs 재귀함수로 풀어봤습니다.
=> 백태균 / 250403 / 개인문제

SWEA/D4/1226. ［S／W 문제해결 기본］ 7일차 － 미로1/README.md, SWEA/D4/1226. ［S／W 문제해결 기본］ 7일차 － 미로1/［S／W 문제해결 기본］ 7일차 － 미로1.py
=> 고영우/ 250410/ 개인문제

SWEA/D2/22654. 차윤이의 RC카/README.md, SWEA/D2/22654. 차윤이의 RC카/차윤이의 RC카.py, SWEA/D2/4871. ［파이썬 S／W 문제해결 기본］ 4일차 － 그래프 경로/README.md, SWEA/D2/4871. ［파이썬 S／W 문제해결 기본］ 4일차 － 그래프 경로/［파이썬 S／W 문제해결 기본］ 4일차 － 그래프 경로.py, SWEA/D4/1226. ［S／W 문제해결 기본］ 7일차 － 미로1/README.md, SWEA/D4/1226. ［S／W 문제해결 기본］ 7일차 － 미로1/［S／W 문제해결 기본］ 7일차 － 미로1.py
배틀 싸피를 위해 풀어보라고 공지사항에 적혀있던 문제 몇 개를 풀어봤습니다.
=> 백태균 / 250413 / 개인문제

백준/Silver/19941. 햄버거 분배/README.md, 백준/Silver/19941. 햄버거 분배/햄버거 분배.py
그리디 문제 하나 풀어봤습니다.
각 사람이 가능한 범위 내에서 가장 왼쪽 햄버거부터 고른다는 느낌으로 접근했습니다.
=> 이상민 / 4월 14일 / 개인문제

백준/Silver/1012. 유기농 배추/README.md, 백준/Silver/1012. 유기농 배추/유기농 배추.py
=> 주선기 / 04월 16일 / 개인문제

SWEA/D2/1983. 조교의 성적 매기기/README.md, SWEA/D2/1983. 조교의 성적 매기기/조교의 성적 매기기.py
딕셔너리를 이용하면 더 짧게 코드 작성이 가능할 거 같습니다.
=> 고영우/ 250422/ 개인문제

백준/Bronze/31090. 2023은 무엇이 특별할까？/2023은 무엇이 특별할까？.py, 백준/Bronze/31090. 2023은 무엇이 특별할까？/README.md
그냥 간단하게 풀어봤습니당
근데 사실 저게 중요한게 아니고요... 스티커 재배치라는 문제를 풀어봤는데,,, 틀렸다고 하더라구요... 헬프 미...ㅠㅠ
=> 곽주혜/5월5일/개인문제

프로그래머스/0/181832. 정수를 나선형으로 배치하기/README.md, 프로그래머스/0/181832. 정수를 나선형으로 배치하기/정수를 나선형으로 배치하기.py
프로그래머스 연습해봤습니당!
옛날에 알고리즘 수업하면서 풀었던 문제인데 오랜만에 하려고 하니까 생각이 잘 안나네요ㅠㅠ 열심히 공부해야겠어요
=> 곽주혜 / 5월 12일 / 개인 문제

프로그래머스/0/181832. 정수를 나선형으로 배치하기/README.md, 프로그래머스/0/181832. 정수를 나선형으로 배치하기/정수를 나선형으로 배치하기.py, 프로그래머스/1/389478. 택배 상자 꺼내기/README.md, 프로그래머스/1/389478. 택배 상자 꺼내기/택배 상자 꺼내기.py
주혜따라서 프로그래머스 문제를 풀어보았어요. 문제 자체는 어렵지 않은데 프로그래머스 형식이 아직은 너무 어색해요 ㅎ
추가적으로 레벨1문제 풀어보았는데 배열만 잘 짜면 되는 문제였어서 정수를 나선형을 배치하기 문제와 유사했습니다!
=> 조현아/5월13일/개인문제

프로그래머스/3/49189. 가장 먼 노드/README.md, 프로그래머스/3/49189. 가장 먼 노드/가장 먼 노드.py
심심해서 1문제 풀었는데요!!
제가 너무 깊게 생각하는 게 문제인 것 같습니다!!
가중치가 없기 때문에 bfs의 경우 먼저 찾은 값이 최단 경로임이 보장되더라고요! 그래서 bfs 내에서 elif문을 제외하고도 실행됩니다.....ㅎㅎ
=> 곽주혜 / 5월 19일 / 개인문제

백준/Silver/1193. 분수찾기/README.md, 백준/Silver/1193. 분수찾기/분수찾기.py
이번주부터 새로운 마음으로 다시 시작하겠습니다. 파이팅!
=> 강수민/5월 20일/개인 문제
